platform :ios, '6.0'

pod 'SOXAppDelegate',   :path => '..'

target :SOXAppDelegateDemoTests do
	pod 'SOXAppDelegate',   :path => '..'
end

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'SOXAPPDELEGATE_BACKGROUNDMODE_FETCH=1']
    end
  end
end